name: Find latest NAV debian package
on: [workflow_dispatch]

jobs:
  getversion:
    name: "Get latest version of NAV package"
    runs-on: ubuntu-latest
    env:
      PREFERRED_DISTRO: bullseye

    steps:
      - name: Add NAV APT repository
        run: |
          sudo mkdir -p --mode=0755 /etc/apt/keyrings
          curl -fsSL https://nav.uninett.no/debian/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/nav.gpg
          echo "deb [signed-by=/etc/apt/keyrings/nav.gpg] https://nav.uninett.no/debian ${PREFERRED_DISTRO} nav" | sudo tee /etc/apt/sources.list.d/nav.list
          sudo apt-get update

      - name: Get latest NAV version
        id: package
        run: |
          VERSION=$(apt-cache policy nav | awk -F ': ' '/Candidate/ {print $2}')
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Get latest navappliance release
        id: appliance
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
        run: |
          latest_release=$(gh api repos/Uninett/navappliance/releases/latest)
          echo "$latest_release" > latest_release.json
          cat latest_release.json

          version=$(jq -r .tag_name latest_release.json | sed s/^v//)
          echo "version=$version" >> $GITHUB_OUTPUT

      - name: Verify update available
        run: |
          if dpkg --compare-versions ${{ steps.package.outputs.version }} gt ${{ steps.appliance.outputs.version }}; then
              echo "There is a newer package available in the APT repository"
          else
              echo "There is no newer package available in the APT repository"
          fi
