name: Do stuff on releases

on:
  release:
    types:
      - published
      - edited
  workflow_dispatch:
    inputs:
      tags:
        description: 'Tag to build'
        required: true
        type: string

jobs:
  echo-everything:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Echo environment"
        run: |
          echo "Release triggered workflow"
          echo The tags are ${{ inputs.tags }}
          env
