name: Do stuff on releases

on:
  release:
    types:
      - published
      - edited
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}


jobs:
  echo-everything:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        if: ${{ ! inputs.tag }}
        uses: actions/checkout@v3

      - name: Checkout repository at tag
        if: ${{ inputs.tag }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - name: "Echo environment"
        run: |
          echo "Release triggered workflow"
          echo The tag is ${{ inputs.tag }}
          env

      - name: Log in to the Container registry
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}

      - name: Print Docker tags and labels
        run: |
          echo "Tags: ${{ steps.meta.outputs.tags }}"
          echo "Labels: ${{ steps.meta.outputs.labels }}"
