name: Do stuff on releases

on:
  release:
    types:
      - released
      - published
      - edited

jobs:
  echo-everything:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: "Echo environment"
        run: |
          echo "Release triggered workflow"
          env
