name: Do stuff on releases

on:
  release:
    types:
      - published
      - edited
  workflow_dispatch:
    inputs:
      tag:
        description: 'Tag to build'
        required: true
        type: string

jobs:
  echo-everything:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        if: ${{ ! inputs.print_tag }}
        uses: actions/checkout@v3

      - name: Checkout repository at tag
        if: ${{ inputs.print_tags }}
        uses: actions/checkout@v3
        with:
          ref: ${{ inputs.tag }}

      - name: "Echo environment"
        run: |
          echo "Release triggered workflow"
          echo The tag is ${{ inputs.tag }}
          env
